version: '3'

services:
    neo4j:
        image: neo4j:4.3
        # expose:
        #    - '7474:7474'
        #    - '7473:7473'
        #    - '7687:7687'
        # ports:
        #     - '7474:7474'
        #     - '7473:7473'
        #     - '7687:7687'
        environment:
            # - user="neo4j"
            - NEO4J_AUTH=none
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
            - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
            - NEO4JLABS_PLUGINS=["apoc"]

            # - NEO4J_AUTH=neo4j/Andrew_07072002
            # - NEO4J_apoc_uuid_enabled=true
            # - NEO4J_dbms_security_procedures_unrestricted=jwt.security.*,apoc.*,gds.*
            # - NEO4J_apoc_import_file_use__neo4j__config=true
        volumes:
            - $PWD/import:/import
            - $PWD/data:/data
            - $PWD/plugins:/plugins
        restart: always
        healthcheck:
            test: wget http://localhost:7474 || exit 1
            interval: 1s
            timeout: 10s
            retries: 20
            start_period: 3s

    web-app:
        container_name: server
        build: './dev'
        ports:
            - "127.0.0.1:3333:3333"
        depends_on:
            neo4j:
                condition: service_healthy
        volumes:
            - import:/var/lib/neo4j/import
volumes:
  import: